name: "Test Brew"
on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: |
          brew install qt
          brew link qt
          ls /usr/local/lib
          ls /usr/local/lib/cmake
          readlink /usr/local/lib/QtCore.framework